const genres = ['TRAVEL', 'KIDS', 'BUSINESS', 'ART', 'BIOGRAPHY', 'CLASSICS', 'COMICS',
  'CRIME', 'COOKBOOKS', 'COOKING', 'FANTASY', 'FICTION', 'QUEER', 'HISTORY', 'HORROR',
  'COMEDY', 'MANGA', 'MUSIC', 'MYSTERY', 'NONFICTION', 'PARANORMAL', 'PHILOSOPHY', 'POETRY', 'PSYCHOLOGY',
  'RELIGION', 'ROMANCE', 'SCIENCE', 'SCIENCE FICTION', 'SELFHELP', 'SPORTS', 'SPIRITUALITY', 'THRILLER',
  'YOUNGADULT', 'SUSPENSE', 'PHOTOGRAPHY', 'POLITICS']

export default genres